<a href="https://colab.research.google.com/github/waegari/deep-learning-zero-kara-tsukuru/blob/%231-b1-ch03/02_np_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [ ]:
B = np.array([[1, 2], [3, 4], [5, 6]])
print(B)

print(f'np.ndim: {np.ndim(B)}')
print(f'B.shape: {B.shape}')
print(B.shape[0])

[[1 2]
 [3 4]
 [5 6]]
np.ndim: 2
B.shape: (3, 2)
3


##配列の積

In [ ]:
A = np.array([[1,2], [3,4]])
A.shape

B = np.array([[3,4], [5,8]])
B.shape

# ドット積
np.dot(A, B)

array([[13, 20],
       [29, 44]])

In [ ]:
C = np.array([[1,2], [3,4], [5,6]])
D = np.array([7,8])

E = np.dot(C, D)

print(C.shape)
print(D.shape)
print(E.shape)

(3, 2)
(2,)
(3,)


In [ ]:
# in a neural network
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5], [2,4,6]])
print(W.shape)

Y = np.dot(X, W)
print(Y)
print(Y.shape)

(2,)
(2, 3)
[ 5 11 17]
(3,)


##いよいよニューラルネットワークの実装へ


In [ ]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))
def identity_function(x):
  return x

def init_network():
  network = {}
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])

  return network

def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']
  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)
  return y

network = init_network()
print(f'network: \n{network}')

x = np.array([1.0, 0.5])
print(f'x: {x}')
y = forward(network, x)
print(f'y: {y}')

network: 
{'W1': array([[0.1, 0.3, 0.5],
       [0.2, 0.4, 0.6]]), 'b1': array([0.1, 0.2, 0.3]), 'W2': array([[0.1, 0.4],
       [0.2, 0.5],
       [0.3, 0.6]]), 'b2': array([0.1, 0.2]), 'W3': array([[0.1, 0.3],
       [0.2, 0.4]]), 'b3': array([0.1, 0.2])}
x: [1.  0.5]
y: [0.31682708 0.69627909]
