##ソフトマックス関数
$
y_k = \sigma(a_k) = \frac{e^{a_k}}{\sum_{i=1}^{k} e^{a_i}}
$

In [ ]:
import numpy as np

a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a) # 分子
print(exp_a)

sum_exp_a = np.sum(exp_a) # 分母
print(sum_exp_a)

y = exp_a/sum_exp_a # ソフトマックス
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


##ソフトマックス関数の実装上の注意
#オーバーフロー！！
- コンピュータで計算を行う上では、欠陥がある
  - $e^{10}$は20000を超える
  - $e^{1000}$はもはや無限大と見なすことになってしまう("inf")

In [ ]:
print(np.exp(1000))

inf


<ipython-input-5-c2155d66b4f0>:1: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


##改善案
  - 正規化する

In [ ]:
a = np.array([1010, 1000, 990])
# np.exp(a) / np.sum(np.exp(a)) # [nan nan nan]

c = np.max(a) # 1010

a - c # array([  0, -10, -20])

softmax = np.exp(a-c) / np.sum(np.exp(a-c))
print(softmax)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [ ]:
# 実装しよう
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c) # オーバーフローの対策
  sum_exp_a = np.sum(exp_a)
  return exp_a / sum_exp_a